### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by ChillarAnand** [rakeshvar/chamanti_ocr#3]
I have installed all packages. When I try to run scribe it is throwing error

```
(exp) 
chillaranand@pavilion:~/projects/python/ocr/chamanti_ocr on git:master x |
→ python3 scribe.py <(echo 'క<0c4d>ర<0c48>ః') > kraih.txt
Traceback (most recent call last):
  File "scribe.py", line 8, in <module>
    import cffi_wrapper as cp
  File "/home/chillaranand/projects/python/ocr/chamanti_ocr/cffi_wrapper.py", line 6, in <module>
    ffi.include(cairocffi.ffi)
  File "/home/chillaranand/.virtualenvs/exp/lib/python3.5/site-packages/cffi/api.py", line 494, in include
    type(ffi_to_include).__name__,))
TypeError: ffi.include() expects an argument that is also of type cffi.FFI, not 'CompiledFFI'
```

**Comment by rakeshvar** [comment]
You can try with the versions mentioned in the [README.](https://github.com/rakeshvar/chamanti_ocr#pre-requisites) Also, the README is out-dated. You need to run the `train.py` file. I will fix it may be at the end of this month, if you can remind me.

**Comment by ChillarAnand** [comment]
Sure. Thank you.

I tried with versions mentioned in readme and with `train.py` file, still it is throwing same error

```
chillaranand@pavilion:~/projects/python/ocr/chamanti_ocr on git:master o |
→ py train.py 
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    import scribe
  File "/home/chillaranand/projects/python/ocr/chamanti_ocr/scribe.py", line 8, in <module>
    import cffi_wrapper as cp
  File "/home/chillaranand/projects/python/ocr/chamanti_ocr/cffi_wrapper.py", line 5, in <module>
    ffi.include(cairocffi.ffi)
  File "/home/chillaranand/.virtualenvs/exp/lib/python3.5/site-packages/cffi/api.py", line 494, in include
    type(ffi_to_include).__name__,))
TypeError: ffi.include() expects an argument that is also of type cffi.FFI, not 'CompiledFFI'
```

**Comment by ChillarAnand** [comment]
@rakeshvar Any updates on this?
